version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
    - zookeeper
    ports:
    - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "test:1:1"
  k-producer:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "pwd && ls && cd django_kafka_producer && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    stdin_open: true
    tty: true
    container_name: web_kafka_producer
    ports:
      - "8000:8000"
    networks:
      - default
    depends_on:
      - kafka
    links:
      - kafka
  kafka-consumer:
    build:
      context: .
      dockerfile: Dockerfile_consumer
    command: bash -c "pwd && ls && python consumer.py"
    stdin_open: true
    tty: true
    container_name: kafka_consumer_2
    networks:
      - default
    depends_on:
      - kafka
    links:
      - kafka